export const TYPES = {
    CREAR_PRODUCTO: "CREAR_PRODUCTO",
    CONSULTAR_PRODUCTO: "CONSULTAR_PRODUCTO",
    CONSULTAR_NOTAS: "CONSULTAR_NOTAS",
    CONSULTAR_PAGOS: "CONSULTAR_PAGOS",
    CONSULTAR_USUARIOSLISTOS: "CONSULTAR_USUARIOSLISTOS",
    CONSULTAR_ESTADISTICAS: "CONSULTAR_ESTADISTICAS",
    EDITAR_PRODUCTO: "EDITAR_PRODUCTO",
    ELIMINAR_PRODUCTO: "ELIMINAR_PRODUCTO",
    SIN_DATOS: "SIN_DATOS",
    
  } as const;